### ISSUE TITLE
Why there existed "KernelLanguage: Source" in vega20*.yaml under rocBLAS/library/src/blas3/Tensile/Logic/asm_full

### ISSUE THREAD

**Issue by hanjiemicro** [ROCmSoftwarePlatform/Tensile#1131]
### What is the expected behavior
- In wiki link: https://github.com/ROCmSoftwarePlatform/Tensile/wiki/Kernel-Parameters
KernelLanguage: Whether kernels should be written in source code (HIP, OpenCL) or assembly (gfx803, gfx900, ...).

### What actually happens
- I think vega20*.yaml only reserved for Assembly kernel. I am confused why there has multiple source kernels in vega20 configuration. 

### Environment
| Hardware | description |
|-----|-----|
| GPU | Vega20 |
| CPU | AMD |

| Software | version |
|-----|-----|
| ROCK | v3.3 |
| ROCR | v3.3 |
| HCC | v3.3|
| Library | v3.3 |

**Comment by zaliu** [comment]
@hanjiemicro, thanks for your question.  Yes, vega20*.yaml are generally where assembly kernels for the vega 20 (gfx906) are found.  However, we do punt some corner (or not-so-corner) cases to Tensile-generated source kernels.  For instance, when m, n or k is odd, for half precision, we let our compiler do the heavy-lifting.  Whenever we do that, we grouped the source kernels with the assembly kernels.  There is no requirement that vega20*.yaml can only include assembly kernels.

**Comment by hanjiemicro** [comment]
> @hanjiemicro, thanks for your question. Yes, vega20*.yaml are generally where assembly kernels for the vega 20 (gfx906) are found. However, we do punt some corner (or not-so-corner) cases to Tensile-generated source kernels. For instance, when m, n or k is odd, for half precision, we let our compiler do the heavy-lifting. Whenever we do that, we grouped the source kernels with the assembly kernels. There is no requirement that vega20*.yaml can only include assembly kernels.
> 
> (BTW, if you're using ROCm 3.5, there shouldn't be hcc as part of the distribution anymore; only HIP-Clang based hipcc is supplied)

Thanks for your feedback. Acutally I tried to modified some kernels' KernelLanugage from "Source" to "Assembly" in vega20_sgemm*.yaml, it worked and dumped assembly kernels. Could you help to explain the corner case further?

**Comment by babakpst** [comment]
As @zaliu mentioned, for some cases where the assembly kernel does not return a good performance, we use source kernels. The corner cases are usually very small sizes. 
Please let us know if you have further questions.
