### ISSUE TITLE
How to use the parameter : 'DirectToLds'

### ISSUE THREAD

**Issue by shana34** [ROCmSoftwarePlatform/Tensile#1168]
After reading the source code in 'Common.py' & 'KernelWritterAssembly.py'. I wonder how 'DirectToLds' make sense. It is initialized as False and do not change with 'DirectToLds= [ True ]' even if I am sure that 'GlobalVectorWidth = 1'
    Another question about this is in 'KernelWritterAssembly.py'. When 'PrefetchGlobalRead' is set, what if 'DirectToLds = True'?
Here is the Code.
![image](https://user-images.githubusercontent.com/22281195/93994106-17066800-fdc2-11ea-8026-6b6c1e9cee4f.png)

**Comment by FFFLJL** [comment]
I had the same problem, the condition of 'DirectToLds' is too harsh

**Comment by babakpst** [comment]
As you mentioned, DirectToLDS is only limited to a few cases. We have relaxed some of the restrictions, but DirectToLDS still requires specific conditions to work.
