### ISSUE TITLE
Stop calling dpkg

### ISSUE THREAD

**Issue by haampie** [ROCmSoftwarePlatform/Tensile#1172]
Could you please stop calling `dpkg` as part of the build?

I'm referring to: https://github.com/ROCmSoftwarePlatform/Tensile/blob/rocm-3.8.0/Tensile/Common.py#L1516-L1536

This suddenly deals with a system-wide installation, and as outlined in the comment, _will not_ work with different package managers, in particular package managers you don't support (AUR / Spack, snap? etc etc). Also, it will not work when _multiple_ versions of rocm packages are installed next to one another; this is what some package managers allow you to do. Also, installations might not be system-wide at all.

Why wouldn't you just call `hipcc --version` / `hcc --version` instead?

**Comment by haampie** [comment]
This is still the case in 4.0.0 unfortunately. Has this issue been noted? (Pinging @TorreZuk :sweat_smile:)

https://github.com/ROCmSoftwarePlatform/Tensile/blob/rocm-4.0.0/Tensile/Common.py#L1575-L1592

**Comment by TorreZuk** [comment]
Sorry @haampie it looks like this will still be true for 4.1, I would hope someone can fix it for 4.2.   Agreed just using hipcc --version or the clang++ --version is better.   I'll also push to see if this can be assigned for the current sprint.

**Comment by zaliu** [comment]
Thanks @haampie for reporting it.  We'll get it fixed for 4.2.  I'll keep you posted.

**Comment by JeremyAdamHart** [comment]
@zaliu, Looks like this issue can be closed? I see that the fix is in the most recent release.

**Comment by zaliu** [comment]
Yes, but normally the person reporting the issue gets t close the ticket.  @haampie?

**Comment by haampie** [comment]
Looks like it! Thanks!
