### ISSUE TITLE
About add new functions to Tensile

### ISSUE THREAD

**Issue by FFFLJL** [ROCmSoftwarePlatform/Tensile#1194]
I would like to add some new functions to Tensile, so that the auto tuning of GEMM can generate the assembly kernel that uses less vgpr than before.
This will expand the range of combinations of parameters, and will increase the CU occupancy,  Finally, tensile may be able to generate kernels with better performance than before.
So could you please give me some help on how to modify the Python code of generating assembly kernel, because the code of Tensile is too large.

**Comment by bragadeesh** [comment]
If you are looking for specific performance improvement, you can provide us with GEMM sizes/datatypes and target devices, and we can look at it.

If I understand correctly, there 2 parts to the question:
1. You would like to do some auto-tuning to improve GEMM performance
2. You are interested in modifying the python generator code to make optimal GPU kernels

Doing # 1 is relatively easy compared to # 2. 

For # 1, Tuning scripts and documentations are available at: https://github.com/ROCmSoftwarePlatform/Tensile/tree/develop/tuning
and https://github.com/ROCmSoftwarePlatform/Tensile/tree/develop/tuning_docs


For # 2, good understanding of the Tensile code structure and related GPU optimization knowledge is needed. We do not have any comprehensive learning materials to support this at this time.

**Comment by FFFLJL** [comment]
> If you are looking for specific performance improvement, you can provide us with GEMM sizes/datatypes and target devices, and we can look at it.
> 
> If I understand correctly, there 2 parts to the question:
> 
> 1. You would like to do some auto-tuning to improve GEMM performance
> 2. You are interested in modifying the python generator code to make optimal GPU kernels
> 
> Doing # 1 is relatively easy compared to # 2.
> 
> For # 1, Tuning scripts and documentations are available at: https://github.com/ROCmSoftwarePlatform/Tensile/tree/develop/tuning
> and https://github.com/ROCmSoftwarePlatform/Tensile/tree/develop/tuning_docs
> 
> For # 2, good understanding of the Tensile code structure and related GPU optimization knowledge is needed. We do not have any comprehensive learning materials to support this at this time.

Thanks for your reply, I am doing some work on #2. I will try to modify tensile by myself and may ask more specific questions later.

**Comment by bragadeesh** [comment]
Thanks, closing this for now.
