### ISSUE TITLE
NoCI still triggers CI 

### ISSUE THREAD

**Issue by solaslin** [ROCmSoftwarePlatform/Tensile#1206]
As title, even a draft PR + NoCI still triggers CI. Is this expected ?

**Comment by rosenrodt** [comment]
According the internal [doc](http://confluence.amd.com/display/MLSE/Github+PR+Labels), the NoCI tag still triggers CI but should be aborted immediately. Since all jobs marked "NoCI" are still running as if it's completely normal, no I am not seeing this as an expected behavior

**Comment by leekillough** [comment]
We use the `noCI` label for PRs which do not require unit tests of libraries, such as documentation-only changes. However, right now, the CI system marks `noCI` tests as having "failed" the tests required for PR merging, so it sort of defeats the purpose of the `noCI` label.

**Comment by saadrahim** [comment]
The goal was to mark the tests as aborted and not impact PRs. It appears that this is not working as well as intended. @eidenyoshida and I will take a look.

**Comment by rosenrodt** [comment]
I am looking at extending the `integration` CI pipeline in PR #1146 to do a full validation of *all* Tensile-generated kernels in rocBLAS. As the full validation shouldn't be done as often, I have an interest in seeing this work

**Comment by eidenyoshida** [comment]
Looks like someone edited the original 'noCI' label in Tensile GitHub to become 'NoCI'. math-CI was looking for an exact match but I have put in a PR into rocJenkins to allow for case insensitive match. Should be fixed shortly. Thanks

**Comment by leekillough** [comment]
Hmm...

**Comment by rosenrodt** [comment]
If the current match pattern looks like `^(?!.*noCI).*$`, maybe changing it to `^(?!.*[Nn][Oo][Cc][Ii]).*$` would enable case-insensitive match?

**Comment by saadrahim** [comment]
@eidenyoshida fixed the code to be case insenstive. This issue shouldn't occur again.
