### ISSUE TITLE
SGEMM benchmark config for Vega FE?

### ISSUE THREAD

**Issue by eqy** [ROCmSoftwarePlatform/Tensile#122]
Hi,

I'm experimenting with SGEMM performance tuning on Vega FE and get around 5 GFLOP/s max with the 5760 benchmark config. I was wondering if there was a pointer to a current best config for Vega/Vega FE that I could use as a starting point that was closer to peak performance?

Thanks,

Eddie

**Comment by guacamoleo** [comment]
If you mean you were using sgemm_5760.yaml, that produces HIP kernels and 5 TFlops does sound like the best that our compiler can do at this time.
If you use sgemm_asm.yaml, then Tensile will produce assembly kernels and you should see over 90% efficiency.

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

**Comment by eqy** [comment]
It is possible to run an apples-to-apples comparison with the sgemm_5760 config (in terms of input size) with the sgemm_asm.yaml config? 
I'm getting `terminate called after throwing an instance of 'std::bad_alloc'` so I'm not sure if that's due to an input size that is too large.

**Comment by guacamoleo** [comment]
sgemm_5760.yaml is an example of non-batched gemm while sgemm_asm.yaml is an example of batched gemm. In the sgemm_asm.yaml file, find all instances of “Batched: True” and change to False. This should make the two much more similar.


David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

**Comment by eqy** [comment]
Great, thanks!
