### ISSUE TITLE
How to get both LdcEqualsLdd as true and false in rocblas logic yaml?

### ISSUE THREAD

**Issue by hanjiemicro** [ROCmSoftwarePlatform/Tensile#1252]
Each yaml file has 2 groups of solutions under rocBLAS/library/src/blas3/Tensile/Logic/asm_full.
The only difference between the 2 groups is parameter: LdcEqualsLdd. 
How did you train tensile to get this yaml?

**Comment by zaliu** [comment]
There is a massage script under Tensile/Logic/archive that does the replication.  If a logic file needs the replication, the original logic file is archived in the Tensile/Logic/archive directory.  Place the logic files to be massaged in a working directory e.g. /tmp/raw, and create an output directory e.g. /tmp/massaged, then just run `python massage.py /tmp/raw /tmp/massaged`.  Then copy /tmp/massaged/* over to Tensile/Logic/asm_full.

Just FYI, this aspect of the logic files is evolving.  A better approach may be introduced in the future.  Hope this answers your question.  Thanks for your interest.
