### ISSUE TITLE
How to point an ISA in yaml (example)?

### ISSUE THREAD

**Issue by vasslavich** [ROCmSoftwarePlatform/Tensile#1412]
Hello, 
could you please to give an example how to point an ISA parameter in section "BenchmarkCommonParameters" of yaml file?

That 

```
BenchmarkCommonParameters:
     - ISA: [(9, 0, 8)]
```

or 

`   -ISA: [9, 0, 8]`

is wrong.

Thank!

**Comment by benjaminulmer** [comment]
What are you trying to accomplish by setting the value for ISA here? Setting the ISA in the Tensile benchmark config yaml is not something we support.
