### ISSUE TITLE
rocblas installation fails during Tensile run with os.fork(): OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by UweSauter** [ROCmSoftwarePlatform/Tensile#1415]
Please have a look at spack/spack/issues/26400

**Comment by benjaminulmer** [comment]
#1440 should help with limiting the amount of memory Tensile uses, although I don't think rocBLAS is making use of the changes yet.

**Comment by TorreZuk** [comment]
In a future releases of rocBLAS https://github.com/ROCmSoftwarePlatform/rocBLAS/commit/0ffee0626bf987bae6b81183a5c61569a489537a  there is a new install.sh argument  -j <N> to be used by make/ninja for parallel build control and will be passed down to Tensile build.   It will just set the cmake argument exposed in the PR mentioned by Ben.
