### ISSUE TITLE
GlobalReadCoalesceGroupA[B] leads to wrong results

### ISSUE THREAD

**Issue by vasslavich** [ROCmSoftwarePlatform/Tensile#1426]
Hello!
I'm experimenting with *.yaml configurations and it is not clearly for me - can I uses GlobalReadCoalesceGroupA[B] for not transposed A and B inputs? Set option to GlobalReadCoalesceGroupA[B] : [False] in *.yaml leads to an incorrect result.
Thanks!

**Comment by bragadeesh** [comment]
Closing old issue; Please reopen if still relevant, after testing latest version of Tensile. If opening again, please identify key info such as GPU/device information and Tensile version and rocm version
