### ISSUE TITLE
Set constStrideC0 to 0 instead of 1

### ISSUE THREAD

**Issue by NevesLucas** [ROCmSoftwarePlatform/Tensile#1515]
Is it possible to generate kernels where constStrideC0I is always 0 instead of 1, while keeping constStrideD0I = 1, essentially converting the C matrix into a vector along J ? (for Cijk_Ailk_Bljk)

**Comment by bragadeesh** [comment]
Closing; if issue is still relevant @NevesLucas  to follow up with @jichangjichang
