### ISSUE TITLE
Asking for advices about tuning small GEMM with large batch count 

### ISSUE THREAD

**Issue by littlewu2508** [ROCmSoftwarePlatform/Tensile#1565]
Hello, my computation involves large amount of matrix multiplication with one or two extremely small size, typically (m,n,k) = (80,800,2), (80,2,800) or (2, 2, 800). The current performance is not ideal, `rocblas-bench` shows that GPU Gflops is only about 5% of its ideal performance (e.g. (m,n,k)=(4096,4096,4096))

I tried to focus on such problems by fixing `ProblemSizes` to my interested size in `BenchmarkFinalParameters`, and search the kernel parameter space to see whether there can be performance improvement. However I met a lot of parameters conflicts, and I found out that the parameter space is indeed huge.

I am not an expert on BLAS and GPGPU, so I'm afraid blindly searching all the parameter space may not work well for me. So, I would like to ask for some advices here.

**Comment by littlewu2508** [comment]
So the question is, what is the preferable configuration for batched sGEMM with one or two dimension = 2? 

How should I set the search range of `ThreadTile`, `WorkGroup`, `WorkGroupMapping` and other parameters? 

Is there some magic parameters for small GEMM problems?

**Comment by benjaminulmer** [comment]
Those sizes are all going to be memory limited as opposed to compute limited, so unfortunately, there's a pretty hard performance ceiling. Larger batch counts can help improve compute unit utilization, but that will only help so much with these problem sizes. 

Going off my gut instinct, 5% of peak performance actually sounds pretty reasonable for those sizes. You might be able to squeeze a few extra percentage points out with the right tuning parameters, but I don't suspect there are any large gains possible.

**Comment by babakpst** [comment]
As Ben mentioned, for these skinny sizes, we cannot design a set of parameters that fully employs the accelerator/GPGPU features. These are small sizes that cannot fully occupy the accelerator, and the performance cannot go up much further.

**Comment by littlewu2508** [comment]
Thanks! Now I understand this question is not trivial, so seems there is no simple solution, and requires more investigation. I'll close this issue, but if (I find) something interesting happens in the future, I'll post and reopen it again.
