### ISSUE TITLE
Rouding error with Gfx90aFp16altSupport

### ISSUE THREAD

**Issue by sumin-hong** [ROCmSoftwarePlatform/Tensile#1583]
Hello, I am trying to training some models using half precision on MI100 and MI250. 

However, unlike MI100, training on MI250 has many challenges due to numerical errors in Gemm and Conv calculations.

First, I already checked that MFMA half computation on MI250 does not handle denorm value properly, so now I'm trying to use the Fp16alt option.

But, using the Fp16alt option, it has more numerical errors than I expected. I think the reason of numerical errors is the absence of rounding mode such as rounding-to-nearest-even, in the process of converting half to bfloat16.

I'd like to get some help on this issue. 
Best regards,

**Comment by bragadeesh** [comment]
Closing, as we are following up on this separately
