### ISSUE TITLE
tensile not completing assembly code for sgemm

### ISSUE THREAD

**Issue by computingdolas** [ROCmSoftwarePlatform/Tensile#300]
Memory access fault by GPU node-2 on address 0x4100000000. Reason: Page not present or supervisor privilege.

Details : 

OS : centos 7
Driver rocm1.8 
GPU : AMD Pro SSG
Can anybody help in this scenario ?

Best,
Sagar

**Comment by sunway513** [comment]
Hi @computingdolas, as @dagamayank mentioned in another thread, your GPU (AMD Pro SSG) is not in ROCM support list.

**Comment by computingdolas** [comment]
Then the real question is, whether roc support is entitled to be supported to radeon instinct GPUs ?

**Comment by sunway513** [comment]
Hi @computingdolas , ROCm support is not entitled to Radeon Instinct GPUs only; however, we do have an official support list here:
https://rocm.github.io/hardware.html

**Comment by computingdolas** [comment]
Thanks @sunway513 . It was informative 👍
