### ISSUE TITLE
LLVM version requirements on master branch

### ISSUE THREAD

**Issue by daniellowell** [ROCmSoftwarePlatform/Tensile#692]
I've updated our at PR in our CI to rocBLAS commit hash: 45dce72985fadcc9e9ca7c52a64311f26b506cfb

Which has the latest master branch for Tensile. There is some LLVM requirement that is not allowing our build to complete. Did the LLVM version change recently?

```
CMake Error at /usr/local/cget/build/tmp-76df881074ee43768f8c4d0236b39e32/build/virtualenv/lib/python3.5/site-packages/Tensile/Source/lib/CMakeLists.txt:48 (find_package):

  Could not find a configuration file for package "LLVM" that is compatible with requested version "7.0".

  The following configuration files were considered but not accepted:
    /usr/share/llvm-3.8/cmake/LLVMConfig.cmake, version: 3.8.0

-- Configuring incomplete, errors occurred!
```

**Comment by zjin-lcf** [comment]
The question is : can we use LLVM 10.0 for Tensile ?

=========================================================
CMake Error at build/release/virtualenv/lib/python3.7/site-packages/Tensile/Source/lib/CMakeLists.txt:48 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "7.0".

**Comment by bragadeesh** [comment]
Closing this for now, please reopen if still relevant
