### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by VincentJing** [ROCmSoftwarePlatform/Tensile#750]
when I run the Tensile use the command `python3 ../Tensile/bin/Tensile ../Tensile/Configs/rocblas_sgemm_asm_only.yaml ./`, I got the result such as follows:

![image](https://user-images.githubusercontent.com/20381269/70974426-b172a600-20e2-11ea-8b39-f4c30ff4e636.png)
I'm sure that I have the power to access the file `/public/home/caspra69/Tensile/build/1_BenchmarkProblems/Cijk_Ailk_Bljk_SB_00/Data/00_Final.csv`

why?

**Comment by bragadeesh** [comment]
Closing for now; please reopen if this is still relevant, and please provide additional information such as GPU used and ROCm version etc.
